services:
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    links:
      - back

  back:
    build: ./docker/back
    volumes:
      - ./:/var/www
    user: 1000:1000
    links:
      - db

  db:
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: example
        MYSQL_DATABASE: tasktracker
        MYSQL_USER: dev
        MYSQL_PASSWORD: secret

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080